services:
  postgres:
    image: postgres:14.3-alpine3.15
    ports:
        - 5431:5432
    env_file:
      - pg.env
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d netology_stocks_products"] #, "-h", "127.0.0.1", "-p", "5431"]
      interval: 5s
      timeout: 6s
      retries: 5

  backend:
    build: .
    env_file:
      - _env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - "bash"
      - "backendStartup.sh"
    volumes:
      - backend-data:/stocks_products_app/
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - backend-data:/stocks_products_app

    depends_on:
      - backend

volumes:
  pgdata2:
    driver: local
  backend-data:
    driver: local
