name: Test Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.3-alpine3.15
        env:
          POSTGRES_USER: diplom_user
          POSTGRES_PASSWORD: your_secure_password
          POSTGRES_DB: netology_pd_diplom
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coverage

    - name: Run tests with coverage
      env:
        DATABASE_URL: postgresql://diplom_user:your_secure_password@localhost:5432/netology_pd_diplom
        REDIS_URL: redis://localhost:6379/0
      run: |
        coverage run --source='.' -m pytest
        coverage xml -i

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
